#!/usr/bin/env python3
"""
ZAID PERSONAL CRYPTO TRADING BOT - Stage 21
Micro Soul Logger Module
Logs spoofing traps and fill misses to SOUL.md
Records exact microsecond timestamps for adverse selection events
Optimized for 8GB RAM with strict type hinting
"""

from __future__ import annotations
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Any
from enum import Enum
import time
import json
from pathlib import Path
from datetime import datetime


class EventType(Enum):
    """Types of microstructure events to log."""
    SPOOFING_TRAP = "spoofing_trap"
    FILL_MISS = "fill_miss"
    ADVERSE_SELECTION = "adverse_selection"
    FAKE_LIQUIDITY_AVOIDED = "fake_liquidity_avoided"
    QUEUE_POSITION_LOST = "queue_position_lost"
    RAPID_CANCEL_DETECTED = "rapid_cancel_detected"
    LAYERING_AVOIDED = "layering_avoided"
    VPIN_SPIKE = "vpin_spike"
    TOXICITY_ALERT = "toxicity_alert"
    EXECUTION_ADJUSTMENT = "execution_adjustment"


@dataclass(slots=True)
class MicroEvent:
    """
    Represents a microstructure event for logging.
    Uses __slots__ for memory efficiency.
    """
    timestamp_ns: int
    event_type: EventType
    symbol: str
    price: float
    volume: float
    side: str
    description: str
    metadata: Dict[str, Any] = field(default_factory=dict)
    prevented_loss_inr: float = 0.0
    missed_profit_inr: float = 0.0
    confidence_score: float = 0.0
    
    @property
    def timestamp_us(self) -> int:
        """Get timestamp in microseconds."""
        return self.timestamp_ns // 1000
    
    @property
    def timestamp_ms(self) -> int:
        """Get timestamp in milliseconds."""
        return self.timestamp_ns // 1_000_000
    
    @property
    def datetime_iso(self) -> str:
        """Get ISO format datetime string."""
        dt = datetime.fromtimestamp(self.timestamp_ns / 1_000_000_000)
        return dt.isoformat()


class MicroSoulLogger:
    """
    Logs microstructure events to SOUL.md file.
    
    Key features:
    - Records exact microsecond timestamps
    - Tracks spoofing traps avoided
    - Logs fill misses with root cause analysis
    - Documents adverse selection prevention
    - Maintains running statistics
    
    Thread-safe for concurrent access.
    """
    
    # Default SOUL.md location
    DEFAULT_SOUL_PATH = Path("SOUL.md")
    
    # Maximum events to keep in memory
    MAX_MEMORY_EVENTS = 10000
    
    def __init__(self, soul_path: str = None, auto_flush: bool = True):
        """
        Initialize micro soul logger.
        
        Args:
            soul_path: Path to SOUL.md file
            auto_flush: Whether to flush after each event
        """
        self.soul_path = Path(soul_path) if soul_path else self.DEFAULT_SOUL_PATH
        self.auto_flush = auto_flush
        
        # In-memory event buffer
        self.events: List[MicroEvent] = []
        
        # Statistics tracking
        self.stats = {
            'total_events': 0,
            'spoofing_traps_logged': 0,
            'fill_misses_logged': 0,
            'adverse_selection_prevented': 0,
            'fake_liquidity_avoided': 0,
            'total_loss_prevented_inr': 0.0,
            'total_missed_profit_inr': 0.0,
            'avg_confidence_score': 0.0,
        }
        
        # Ensure SOUL.md exists with header
        self._ensure_soul_file()
    
    def _ensure_soul_file(self) -> None:
        """Create SOUL.md with header if it doesn't exist."""
        if not self.soul_path.exists():
            self.soul_path.parent.mkdir(parents=True, exist_ok=True)
            
            header = """# ZAID PERSONAL CRYPTO TRADING BOT - SOUL.md

## Microstructure Event Log

This file contains the complete log of microstructure events including:
- Spoofing traps detected and avoided
- Fill misses with root cause analysis
- Adverse selection prevention events
- Fake liquidity walls identified
- Queue position tracking anomalies

Generated by MicroSoulLogger (Stage 21)

---

"""
            with open(self.soul_path, 'w') as f:
                f.write(header)
    
    def log_event(self, event: MicroEvent) -> None:
        """
        Log a microstructure event.
        
        Args:
            event: MicroEvent to log
        """
        # Add to memory buffer
        self.events.append(event)
        if len(self.events) > self.MAX_MEMORY_EVENTS:
            self.events.pop(0)
        
        # Update statistics
        self._update_stats(event)
        
        # Append to SOUL.md
        self._append_to_soul(event)
        
        if self.auto_flush:
            self.flush()
    
    def log_spoofing_trap(self, symbol: str, price: float, volume: float, 
                          side: str, confidence: float, 
                          prevented_loss_inr: float = 0.0,
                          **metadata) -> None:
        """
        Log a spoofing trap that was detected and avoided.
        
        Args:
            symbol: Trading pair symbol
            price: Price level of spoofing
            volume: Volume of fake order
            side: Bid or Ask
            confidence: Detection confidence (0-1)
            prevented_loss_inr: Estimated loss prevented in INR
            metadata: Additional context
        """
        event = MicroEvent(
            timestamp_ns=time.time_ns(),
            event_type=EventType.SPOOFING_TRAP,
            symbol=symbol,
            price=price,
            volume=volume,
            side=side,
            description=f"Spoofing trap avoided at {price} - {volume} units on {side} side",
            metadata=metadata,
            prevented_loss_inr=prevented_loss_inr,
            confidence_score=confidence,
        )
        self.log_event(event)
    
    def log_fill_miss(self, symbol: str, price: float, volume: float,
                      side: str, reason: str, missed_profit_inr: float = 0.0,
                      queue_position: int = -1, **metadata) -> None:
        """
        Log a fill miss event with root cause.
        
        Args:
            symbol: Trading pair symbol
            price: Intended fill price
            volume: Intended fill volume
            side: Bid or Ask
            reason: Reason for fill miss
            missed_profit_inr: Estimated profit missed in INR
            queue_position: Queue position when order was placed
            metadata: Additional context
        """
        metadata['queue_position'] = queue_position
        metadata['miss_reason'] = reason
        
        event = MicroEvent(
            timestamp_ns=time.time_ns(),
            event_type=EventType.FILL_MISS,
            symbol=symbol,
            price=price,
            volume=volume,
            side=side,
            description=f"Fill miss at {price}: {reason}",
            metadata=metadata,
            missed_profit_inr=missed_profit_inr,
        )
        self.log_event(event)
    
    def log_adverse_selection_prevented(self, symbol: str, price: float,
                                         volume: float, side: str,
                                         vpin_value: float = 0.0,
                                         toxicity_score: float = 0.0,
                                         prevented_loss_inr: float = 0.0,
                                         **metadata) -> None:
        """
        Log an adverse selection event that was prevented.
        
        Args:
            symbol: Trading pair symbol
            price: Price level
            volume: Order volume
            side: Bid or Ask
            vpin_value: VPIN at time of prevention
            toxicity_score: Toxicity score at time of prevention
            prevented_loss_inr: Estimated loss prevented in INR
            metadata: Additional context
        """
        metadata['vpin'] = vpin_value
        metadata['toxicity'] = toxicity_score
        
        event = MicroEvent(
            timestamp_ns=time.time_ns(),
            event_type=EventType.ADVERSE_SELECTION,
            symbol=symbol,
            price=price,
            volume=volume,
            side=side,
            description=f"Adverse selection prevented (VPIN: {vpin_value:.2%}, Toxicity: {toxicity_score:.2%})",
            metadata=metadata,
            prevented_loss_inr=prevented_loss_inr,
            confidence_score=max(vpin_value, toxicity_score),
        )
        self.log_event(event)
    
    def log_fake_liquidity_avoided(self, symbol: str, price: float,
                                    volume: float, side: str,
                                    wall_size: float, confidence: float,
                                    **metadata) -> None:
        """
        Log avoidance of a fake liquidity wall.
        
        Args:
            symbol: Trading pair symbol
            price: Price level of fake wall
            volume: Our intended order volume
            side: Bid or Ask
            wall_size: Size of the fake wall
            confidence: Detection confidence
            metadata: Additional context
        """
        metadata['wall_size'] = wall_size
        
        event = MicroEvent(
            timestamp_ns=time.time_ns(),
            event_type=EventType.FAKE_LIQUIDITY_AVOIDED,
            symbol=symbol,
            price=price,
            volume=volume,
            side=side,
            description=f"Avoided fake liquidity wall of {wall_size} at {price}",
            metadata=metadata,
            confidence_score=confidence,
        )
        self.log_event(event)
    
    def get_events(self, event_type: EventType = None, 
                   limit: int = 100) -> List[MicroEvent]:
        """
        Get recent events from memory buffer.
        
        Args:
            event_type: Filter by event type (None for all)
            limit: Maximum events to return
            
        Returns:
            List of MicroEvent objects
        """
        if event_type is None:
            return self.events[-limit:]
        
        filtered = [e for e in self.events if e.event_type == event_type]
        return filtered[-limit:]
    
    def get_stats(self) -> Dict:
        """Get current statistics."""
        return self.stats.copy()
    
    def flush(self) -> None:
        """Flush any buffered writes (file sync)."""
        # File is already synced after each write
        pass
    
    def clear(self) -> None:
        """Clear in-memory events (does not affect SOUL.md)."""
        self.events.clear()
    
    def _update_stats(self, event: MicroEvent) -> None:
        """Update statistics based on event."""
        self.stats['total_events'] += 1
        
        if event.event_type == EventType.SPOOFING_TRAP:
            self.stats['spoofing_traps_logged'] += 1
        elif event.event_type == EventType.FILL_MISS:
            self.stats['fill_misses_logged'] += 1
        elif event.event_type == EventType.ADVERSE_SELECTION:
            self.stats['adverse_selection_prevented'] += 1
        elif event.event_type == EventType.FAKE_LIQUIDITY_AVOIDED:
            self.stats['fake_liquidity_avoided'] += 1
        
        self.stats['total_loss_prevented_inr'] += event.prevented_loss_inr
        self.stats['total_missed_profit_inr'] += event.missed_profit_inr
        
        # Update running average confidence
        n = self.stats['total_events']
        self.stats['avg_confidence_score'] = (
            (self.stats['avg_confidence_score'] * (n - 1) + event.confidence_score) / n
        )
    
    def _append_to_soul(self, event: MicroEvent) -> None:
        """Append event to SOUL.md file."""
        # Format event entry
        entry = self._format_event_entry(event)
        
        # Append to file
        with open(self.soul_path, 'a') as f:
            f.write(entry)
    
    def _format_event_entry(self, event: MicroEvent) -> str:
        """Format event as markdown entry."""
        # Create timestamp with microsecond precision
        ts_us = event.timestamp_us
        ts_formatted = datetime.fromtimestamp(event.timestamp_ns / 1_000_000_000).strftime(
            '%Y-%m-%d %H:%M:%S.%f'
        )[:-3]  # Millisecond precision for readability
        
        # Build entry
        lines = [
            f"\n### [{event.event_type.value.upper()}] {ts_formatted} (µs: {ts_us})",
            "",
            f"- **Symbol**: {event.symbol}",
            f"- **Price**: {event.price}",
            f"- **Volume**: {event.volume}",
            f"- **Side**: {event.side.upper()}",
            f"- **Description**: {event.description}",
            f"- **Confidence**: {event.confidence_score:.2%}",
        ]
        
        if event.prevented_loss_inr > 0:
            lines.append(f"- **Loss Prevented**: ₹{event.prevented_loss_inr:,.2f} INR")
        
        if event.missed_profit_inr > 0:
            lines.append(f"- **Missed Profit**: ₹{event.missed_profit_inr:,.2f} INR")
        
        if event.metadata:
            lines.append("")
            lines.append("**Metadata**:")
            for key, value in event.metadata.items():
                if isinstance(value, float):
                    lines.append(f"  - {key}: {value:.6f}")
                else:
                    lines.append(f"  - {key}: {value}")
        
        lines.append("")
        lines.append("---")
        lines.append("")
        
        return "\n".join(lines)
    
    def generate_summary(self) -> str:
        """Generate a summary report of logged events."""
        summary_lines = [
            "# Microstructure Event Summary",
            "",
            f"Generated: {datetime.now().isoformat()}",
            "",
            "## Statistics",
            "",
            f"- Total Events Logged: {self.stats['total_events']}",
            f"- Spoofing Traps Detected: {self.stats['spoofing_traps_logged']}",
            f"- Fill Misses Analyzed: {self.stats['fill_misses_logged']}",
            f"- Adverse Selection Prevented: {self.stats['adverse_selection_prevented']}",
            f"- Fake Liquidity Avoided: {self.stats['fake_liquidity_avoided']}",
            "",
            "## Financial Impact",
            "",
            f"- Total Loss Prevented: ₹{self.stats['total_loss_prevented_inr']:,.2f} INR",
            f"- Total Missed Profit: ₹{self.stats['total_missed_profit_inr']:,.2f} INR",
            f"- Net Protection Value: ₹{self.stats['total_loss_prevented_inr'] - self.stats['total_missed_profit_inr']:,.2f} INR",
            "",
            "## Event Type Distribution",
            "",
        ]
        
        # Count by type
        type_counts: Dict[str, int] = {}
        for event in self.events:
            type_name = event.event_type.value
            type_counts[type_name] = type_counts.get(type_name, 0) + 1
        
        for type_name, count in sorted(type_counts.items(), key=lambda x: -x[1]):
            pct = count / len(self.events) * 100 if self.events else 0
            summary_lines.append(f"- {type_name}: {count} ({pct:.1f}%)")
        
        return "\n".join(summary_lines)


if __name__ == "__main__":
    # Example usage and testing
    logger = MicroSoulLogger(auto_flush=True)
    
    # Log various events
    logger.log_spoofing_trap(
        symbol="BTCUSDT",
        price=50000.0,
        volume=100.0,
        side="bid",
        confidence=0.95,
        prevented_loss_inr=50000.0,
        detector="rapid_cancel"
    )
    
    logger.log_fill_miss(
        symbol="ETHUSDT",
        price=3000.0,
        volume=10.0,
        side="ask",
        reason="Queue jumped by larger order",
        missed_profit_inr=5000.0,
        queue_position=5
    )
    
    logger.log_adverse_selection_prevented(
        symbol="BTCUSDT",
        price=49950.0,
        volume=5.0,
        side="bid",
        vpin_value=0.75,
        toxicity_score=0.82,
        prevented_loss_inr=25000.0
    )
    
    logger.log_fake_liquidity_avoided(
        symbol="SOLUSDT",
        price=100.0,
        volume=500.0,
        side="ask",
        wall_size=10000.0,
        confidence=0.88
    )
    
    # Print stats
    stats = logger.get_stats()
    print("Logger Statistics:")
    for key, value in stats.items():
        print(f"  {key}: {value}")
    
    # Generate summary
    summary = logger.generate_summary()
    print(f"\n{summary}")
    
    print(f"\nEvents logged to: {logger.soul_path.absolute()}")
