//! backend/orderflow/trigger_state_machine.rs
//!
//! State machine for firing execution signals only on confirmed absorption.
//! Implements robust state transitions to prevent false triggers.
//!
//! Features:
//! - State-based trigger logic
//! - Multi-condition confirmation requirements
//! - Memory-efficient state tracking
//! - Thread-safe operations
//! - Configurable sensitivity levels

use std::collections::HashMap;
use std::sync::{Arc, RwLock};

/// Execution states in the state machine
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TriggerState {
    Idle,              // Waiting for setup
    Watching,          // Monitoring for potential setup
    AbsorptionDetected, // Absorption pattern identified
    Confirming,        // Waiting for confirmation
    ReadyToExecute,    // All conditions met, ready to fire
    Executing,         // Order being placed
    Cooldown,          // Post-execution cooldown
}

/// Trigger event types
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum TriggerEvent {
    AbsorptionStart,
    AbsorptionConfirmed,
    DivergenceDetected,
    VolumeSpike,
    PriceBreakout,
    ExhaustionSignal,
    Cancellation,
    Timeout,
    ExecutionComplete,
}

/// Execution signal generated by state machine
#[derive(Debug, Clone)]
pub struct ExecutionSignal {
    pub symbol: String,
    pub direction: TradeDirection,
    pub entry_price: f64,
    pub stop_loss: f64,
    pub take_profit: f64,
    pub position_size_pct: f64,
    pub confidence: f64,
    pub trigger_reason: String,
    pub timestamp_ns: u64,
}

/// Trade direction
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum TradeDirection {
    Long,
    Short,
}

/// Configuration for trigger sensitivity
#[derive(Debug, Clone, Copy)]
pub struct TriggerConfig {
    /// Minimum absorption confidence required
    pub min_absorption_confidence: f64,
    /// Number of confirmations needed
    pub required_confirmations: usize,
    /// Cooldown period between trades (nanoseconds)
    pub cooldown_ns: u64,
    /// Timeout for waiting confirmation (nanoseconds)
    pub confirmation_timeout_ns: u64,
    /// Minimum volume for trigger
    pub min_volume: f64,
}

impl Default for TriggerConfig {
    fn default() -> Self {
        Self {
            min_absorption_confidence: 0.7,
            required_confirmations: 2,
            cooldown_ns: 60_000_000_000,  // 1 minute
            confirmation_timeout_ns: 5_000_000_000,  // 5 seconds
            min_volume: 1.0,
        }
    }
}

/// State transition result
#[derive(Debug)]
pub struct TransitionResult {
    pub from_state: TriggerState,
    pub to_state: TriggerState,
    pub triggered_by: TriggerEvent,
    pub should_execute: bool,
    pub signal: Option<ExecutionSignal>,
}

/// State machine for a single symbol
pub struct SymbolStateMachine {
    config: TriggerConfig,
    current_state: TriggerState,
    confirmation_count: usize,
    absorption_price: Option<f64>,
    absorption_type: Option<AbsorptionType>,
    state_entered_ns: u64,
    last_execution_ns: u64,
}

/// Type of absorption triggering the state machine
#[derive(Debug, Clone, Copy)]
pub enum AbsorptionType {
    BidAbsorption,  // Bullish
    AskAbsorption,  // Bearish
}

impl SymbolStateMachine {
    pub fn new(config: TriggerConfig) -> Self {
        Self {
            config,
            current_state: TriggerState::Idle,
            confirmation_count: 0,
            absorption_price: None,
            absorption_type: None,
            state_entered_ns: 0,
            last_execution_ns: 0,
        }
    }
    
    /// Process an event and return transition result
    pub fn process_event(
        &mut self,
        event: TriggerEvent,
        symbol: &str,
        current_price: f64,
        volume: f64,
        ts: u64,
    ) -> Option<TransitionResult> {
        let old_state = self.current_state;
        
        // Check cooldown
        if self.current_state == TriggerState::Cooldown {
            if ts - self.last_execution_ns < self.config.cooldown_ns {
                return None;  // Still in cooldown
            } else {
                self.current_state = TriggerState::Idle;
                self.state_entered_ns = ts;
            }
        }
        
        // State transitions
        let new_state = match (self.current_state, event) {
            // From Idle
            (TriggerState::Idle, TriggerEvent::AbsorptionStart) => {
                self.absorption_price = Some(current_price);
                self.confirmation_count = 1;
                TriggerState::Watching
            }
            
            // From Watching
            (TriggerState::Watching, TriggerEvent::AbsorptionConfirmed) => {
                if volume >= self.config.min_volume {
                    self.confirmation_count += 1;
                    if self.confirmation_count >= self.config.required_confirmations {
                        TriggerState::AbsorptionDetected
                    } else {
                        TriggerState::Watching
                    }
                } else {
                    TriggerState::Watching
                }
            }
            (TriggerState::Watching, TriggerEvent::Timeout) => {
                if ts - self.state_entered_ns > self.config.confirmation_timeout_ns {
                    self.reset();
                    TriggerState::Idle
                } else {
                    TriggerState::Watching
                }
            }
            
            // From AbsorptionDetected
            (TriggerState::AbsorptionDetected, TriggerEvent::DivergenceDetected) => {
                TriggerState::Confirming
            }
            (TriggerState::AbsorptionDetected, TriggerEvent::VolumeSpike) => {
                TriggerState::Confirming
            }
            
            // From Confirming
            (TriggerState::Confirming, TriggerEvent::ExhaustionSignal) => {
                TriggerState::ReadyToExecute
            }
            (TriggerState::Confirming, TriggerEvent::PriceBreakout) => {
                TriggerState::ReadyToExecute
            }
            (TriggerState::Confirming, TriggerEvent::Timeout) => {
                if ts - self.state_entered_ns > self.config.confirmation_timeout_ns {
                    self.reset();
                    TriggerState::Idle
                } else {
                    TriggerState::Confirming
                }
            }
            
            // From ReadyToExecute
            (TriggerState::ReadyToExecute, TriggerEvent::Cancellation) => {
                self.reset();
                TriggerState::Idle
            }
            
            _ => self.current_state,  // No state change
        };
        
        self.current_state = new_state;
        
        // Generate signal if transitioning to ReadyToExecute
        let (should_execute, signal) = if old_state != TriggerState::ReadyToExecute 
            && new_state == TriggerState::ReadyToExecute 
        {
            let direction = match self.absorption_type {
                Some(AbsorptionType::BidAbsorption) => TradeDirection::Long,
                Some(AbsorptionType::AskAbsorption) => TradeDirection::Short,
                None => TradeDirection::Long,  // Default
            };
            
            let signal = self.create_signal(symbol, current_price, direction, ts);
            (true, Some(signal))
        } else {
            (false, None)
        };
        
        if old_state != new_state {
            Some(TransitionResult {
                from_state: old_state,
                to_state: new_state,
                triggered_by: event,
                should_execute,
                signal,
            })
        } else {
            None
        }
    }
    
    /// Set absorption type when first detected
    pub fn set_absorption_type(&mut self, absorption_type: AbsorptionType) {
        self.absorption_type = Some(absorption_type);
    }
    
    /// Manually transition to executing state
    pub fn start_execution(&mut self, ts: u64) {
        self.current_state = TriggerState::Executing;
        self.state_entered_ns = ts;
    }
    
    /// Complete execution and enter cooldown
    pub fn complete_execution(&mut self, ts: u64) {
        self.current_state = TriggerState::Cooldown;
        self.last_execution_ns = ts;
        self.state_entered_ns = ts;
    }
    
    /// Get current state
    pub fn get_state(&self) -> TriggerState {
        self.current_state
    }
    
    /// Reset state machine
    fn reset(&mut self) {
        self.confirmation_count = 0;
        self.absorption_price = None;
        self.absorption_type = None;
    }
    
    /// Create execution signal
    fn create_signal(
        &self,
        symbol: &str,
        current_price: f64,
        direction: TradeDirection,
        ts: u64,
    ) -> ExecutionSignal {
        let (stop_loss, take_profit) = match direction {
            TradeDirection::Long => (
                current_price * 0.995,  // 0.5% stop
                current_price * 1.015,  // 1.5% target
            ),
            TradeDirection::Short => (
                current_price * 1.005,  // 0.5% stop
                current_price * 0.985,  // 1.5% target
            ),
        };
        
        ExecutionSignal {
            symbol: symbol.to_string(),
            direction,
            entry_price: current_price,
            stop_loss,
            take_profit,
            position_size_pct: 0.1,  // 10% position
            confidence: self.calculate_confidence(),
            trigger_reason: format!("Absorption {:?} with {} confirmations", 
                self.absorption_type, self.confirmation_count),
            timestamp_ns: ts,
        }
    }
    
    /// Calculate confidence based on confirmations and state duration
    fn calculate_confidence(&self) -> f64 {
        let base = 0.5;
        let confirmation_bonus = (self.confirmation_count as f64 * 0.1).min(0.3);
        base + confirmation_bonus
    }
}

/// Manager for state machines across multiple symbols
pub struct TriggerStateMachineManager {
    machines: HashMap<String, SymbolStateMachine>,
    config: TriggerConfig,
    observers: Vec<Box<dyn TriggerObserver>>,
}

/// Observer trait for trigger notifications
pub trait TriggerObserver: Send + Sync {
    fn on_state_change(&self, symbol: &str, from: TriggerState, to: TriggerState);
    fn on_execution_signal(&self, signal: &ExecutionSignal);
}

impl TriggerStateMachineManager {
    pub fn new(config: TriggerConfig) -> Self {
        Self {
            machines: HashMap::new(),
            config,
            observers: Vec::new(),
        }
    }
    
    pub fn add_observer(&mut self, observer: Box<dyn TriggerObserver>) {
        self.observers.push(observer);
    }
    
    fn get_or_create_machine(&mut self, symbol: &str) -> &mut SymbolStateMachine {
        self.machines
            .entry(symbol.to_string())
            .or_insert_with(|| SymbolStateMachine::new(self.config))
    }
    
    /// Process an event for a symbol
    pub fn process_event(
        &mut self,
        symbol: &str,
        event: TriggerEvent,
        price: f64,
        volume: f64,
        ts: u64,
    ) -> Option<TransitionResult> {
        let machine = self.get_or_create_machine(symbol);
        
        if let Some(result) = machine.process_event(event, symbol, price, volume, ts) {
            // Notify observers
            for observer in &self.observers {
                observer.on_state_change(symbol, result.from_state, result.to_state);
                
                if let Some(ref signal) = result.signal {
                    observer.on_execution_signal(signal);
                }
            }
            
            Some(result)
        } else {
            None
        }
    }
    
    /// Get state for a symbol
    pub fn get_state(&self, symbol: &str) -> Option<TriggerState> {
        self.machines.get(symbol).map(|m| m.get_state())
    }
    
    /// Get all states summary
    pub fn get_all_states(&self) -> HashMap<String, TriggerState> {
        self.machines
            .iter()
            .map(|(symbol, machine)| (symbol.clone(), machine.get_state()))
            .collect()
    }
}

impl Default for TriggerStateMachineManager {
    fn default() -> Self {
        Self::new(TriggerConfig::default())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn test_state_transitions() {
        let mut machine = SymbolStateMachine::new(TriggerConfig::default());
        
        // Start with Idle
        assert_eq!(machine.get_state(), TriggerState::Idle);
        
        // Absorption start
        let result = machine.process_event(
            TriggerEvent::AbsorptionStart,
            "BTCUSDT",
            60000.0,
            5.0,
            1000
        );
        
        assert!(result.is_some());
        assert_eq!(result.as_ref().unwrap().to_state, TriggerState::Watching);
        
        // Absorption confirmed
        let result = machine.process_event(
            TriggerEvent::AbsorptionConfirmed,
            "BTCUSDT",
            60000.0,
            10.0,
            2000
        );
        
        assert!(result.is_some());
        assert_eq!(result.as_ref().unwrap().to_state, TriggerState::Watching);
    }
}
