//! Correlation Breaker - Hedge Failure Detection
//! 
//! This module detects when hedges fail due to correlation breakdown between
//! spot and perpetual markets, or between different assets used for cross-hedging.
//! 
//! Key Features:
//! - Real-time correlation monitoring with rolling windows
//! - Statistical significance testing for correlation breaks
//! - Automatic hedge suspension during regime changes
//! - Zero-cost abstractions for memory efficiency
//! 
//! Target: Detect correlation breakdowns before they cause significant losses

use std::collections::{VecDeque, HashMap};
use std::sync::{Arc, Mutex};
use std::time::{Duration, Instant};
use std::fmt::{Debug, Display};

/// Asset pair for correlation tracking
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct AssetPair {
    pub base: Asset,
    pub quote: Asset,
}

impl AssetPair {
    pub fn new(base: Asset, quote: Asset) -> Self {
        Self { base, quote }
    }
    
    /// Create canonical representation (sorted) for consistent hashing
    pub fn canonical(&self) -> Self {
        if self.base as u8 > self.quote as u8 {
            Self { base: self.quote, quote: self.base }
        } else {
            *self
        }
    }
}

/// Supported assets
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Asset {
    BTC,
    ETH,
    SOL,
    USDT,
}

impl Display for Asset {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Asset::BTC => write!(f, "BTC"),
            Asset::ETH => write!(f, "ETH"),
            Asset::SOL => write!(f, "SOL"),
            Asset::USDT => write!(f, "USDT"),
        }
    }
}

/// Price return data point
#[derive(Debug, Clone)]
pub struct ReturnObservation {
    pub timestamp: Instant,
    pub return_pct: f64,
}

/// Correlation state between two assets
#[derive(Debug)]
pub struct CorrelationState {
    pub pair: AssetPair,
    pub current_correlation: f64,
    pub historical_mean: f64,
    pub historical_std: f64,
    pub z_score: f64,
    pub sample_count: usize,
    pub last_updated: Instant,
    pub regime: CorrelationRegime,
}

/// Correlation regime classification
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CorrelationRegime {
    Normal,      // Within 1 std of mean
    Elevated,    // 1-2 std from mean
    Extreme,     // 2+ std from mean
    Broken,      // Statistically significant break
}

impl Display for CorrelationRegime {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            CorrelationRegime::Normal => write!(f, "Normal"),
            CorrelationRegime::Elevated => write!(f, "Elevated"),
            CorrelationRegime::Extreme => write!(f, "Extreme"),
            CorrelationRegime::Broken => write!(f, "Broken"),
        }
    }
}

/// Alert generated by correlation breaker
#[derive(Debug)]
pub struct CorrelationAlert {
    pub pair: AssetPair,
    pub alert_type: AlertType,
    pub severity: Severity,
    pub current_correlation: f64,
    pub expected_correlation: f64,
    pub z_score: f64,
    pub timestamp: Instant,
    pub message: String,
    pub recommended_action: RecommendedAction,
}

/// Type of correlation alert
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AlertType {
    CorrelationBreakdown,
    CorrelationSpike,
    RegimeChange,
    HedgeFailure,
    BasisBlowout,
}

/// Alert severity levels
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Severity {
    Low,
    Medium,
    High,
    Critical,
}

impl Display for Severity {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Severity::Low => write!(f, "Low"),
            Severity::Medium => write!(f, "Medium"),
            Severity::High => write!(f, "High"),
            Severity::Critical => write!(f, "Critical"),
        }
    }
}

/// Recommended action for trader/system
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RecommendedAction {
    Monitor,
    ReduceHedgeSize,
    SuspendHedging,
    RebalanceImmediately,
    SwitchHedgeInstrument,
}

impl Display for RecommendedAction {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            RecommendedAction::Monitor => write!(f, "Monitor"),
            RecommendedAction::ReduceHedgeSize => write!(f, "ReduceHedgeSize"),
            RecommendedAction::SuspendHedging => write!(f, "SuspendHedging"),
            RecommendedAction::RebalanceImmediately => write!(f, "RebalanceImmediately"),
            RecommendedAction::SwitchHedgeInstrument => write!(f, "SwitchHedgeInstrument"),
        }
    }
}

/// Rolling window statistics calculator (zero heap allocation after initialization)
pub struct RollingStatistics {
    window_size: usize,
    observations: VecDeque<f64>,
    sum: f64,
    sum_sq: f64,
}

impl RollingStatistics {
    pub fn new(window_size: usize) -> Self {
        Self {
            window_size,
            observations: VecDeque::with_capacity(window_size),
            sum: 0.0,
            sum_sq: 0.0,
        }
    }
    
    /// Add observation and update running statistics
    pub fn add(&mut self, value: f64) {
        // Remove oldest if at capacity
        if self.observations.len() >= self.window_size {
            if let Some(old) = self.observations.pop_front() {
                self.sum -= old;
                self.sum_sq -= old * old;
            }
        }
        
        // Add new observation
        self.observations.push_back(value);
        self.sum += value;
        self.sum_sq += value * value;
    }
    
    /// Calculate mean of rolling window
    pub fn mean(&self) -> f64 {
        let n = self.observations.len() as f64;
        if n == 0.0 { return 0.0; }
        self.sum / n
    }
    
    /// Calculate standard deviation of rolling window
    pub fn std(&self) -> f64 {
        let n = self.observations.len() as f64;
        if n < 2.0 { return 0.0; }
        
        let mean = self.mean();
        let variance = (self.sum_sq / n) - (mean * mean);
        
        // Bessel's correction for sample std
        if variance > 0.0 {
            (variance * n / (n - 1.0)).sqrt()
        } else {
            0.0
        }
    }
    
    /// Get number of observations
    pub fn count(&self) -> usize {
        self.observations.len()
    }
    
    /// Check if window is full
    pub fn is_full(&self) -> bool {
        self.observations.len() >= self.window_size
    }
}

/// Pearson correlation calculator with online updates
pub struct CorrelationCalculator {
    x_stats: RollingStatistics,
    y_stats: RollingStatistics,
    xy_sum: f64,
    x_sum: f64,
    y_sum: f64,
    count: usize,
}

impl CorrelationCalculator {
    pub fn new(window_size: usize) -> Self {
        Self {
            x_stats: RollingStatistics::new(window_size),
            y_stats: RollingStatistics::new(window_size),
            xy_sum: 0.0,
            x_sum: 0.0,
            y_sum: 0.0,
            count: 0,
        }
    }
    
    /// Add paired observation
    pub fn add(&mut self, x: f64, y: f64) {
        self.x_stats.add(x);
        self.y_stats.add(y);
        
        self.x_sum += x;
        self.y_sum += y;
        self.xy_sum += x * y;
        self.count += 1;
    }
    
    /// Calculate Pearson correlation coefficient
    pub fn correlation(&self) -> f64 {
        let n = self.count.min(self.x_stats.count()) as f64;
        if n < 3.0 { return 0.0; } // Need minimum samples
        
        let x_mean = self.x_stats.mean();
        let y_mean = self.y_stats.mean();
        let x_std = self.x_stats.std();
        let y_std = self.y_stats.std();
        
        if x_std == 0.0 || y_std == 0.0 {
            return 0.0;
        }
        
        // Covariance from running sums
        let covariance = (self.xy_sum / n) - (x_mean * y_mean);
        
        // Pearson correlation
        covariance / (x_std * y_std)
    }
}

/// Main correlation breaker engine
pub struct CorrelationBreaker {
    /// Monitored asset pairs
    monitored_pairs: Vec<AssetPair>,
    
    /// Correlation states by pair
    correlation_states: HashMap<AssetPair, CorrelationState>,
    
    /// Rolling calculators for each pair
    calculators: HashMap<AssetPair, CorrelationCalculator>,
    
    /// Historical correlation baselines
    baselines: HashMap<AssetPair, (f64, f64)>, // (mean, std)
    
    /// Alert history
    alerts: Vec<CorrelationAlert>,
    
    /// Configuration
    z_score_threshold: f64,
    min_samples: usize,
    window_size: usize,
    
    /// Current system state
    hedging_suspended: bool,
    suspended_pairs: Vec<AssetPair>,
}

impl CorrelationBreaker {
    /// Create new correlation breaker with default thresholds
    pub fn new(
        z_score_threshold: f64,
        min_samples: usize,
        window_size: usize,
    ) -> Self {
        Self {
            monitored_pairs: Vec::new(),
            correlation_states: HashMap::new(),
            calculators: HashMap::new(),
            baselines: HashMap::new(),
            alerts: Vec::new(),
            z_score_threshold,
            min_samples,
            window_size,
            hedging_suspended: false,
            suspended_pairs: Vec::new(),
        }
    }
    
    /// Add asset pair to monitor
    pub fn add_pair(&mut self, pair: AssetPair) {
        let canonical = pair.canonical();
        
        if !self.monitored_pairs.contains(&canonical) {
            self.monitored_pairs.push(canonical);
            
            self.calculators.insert(
                canonical,
                CorrelationCalculator::new(self.window_size),
            );
            
            self.correlation_states.insert(
                canonical,
                CorrelationState {
                    pair: canonical,
                    current_correlation: 0.0,
                    historical_mean: 0.0,
                    historical_std: 1.0,
                    z_score: 0.0,
                    sample_count: 0,
                    last_updated: Instant::now(),
                    regime: CorrelationRegime::Normal,
                },
            );
        }
    }
    
    /// Set baseline correlation for a pair (from historical data)
    pub fn set_baseline(&mut self, pair: AssetPair, mean: f64, std: f64) {
        let canonical = pair.canonical();
        self.baselines.insert(canonical, (mean, std));
        
        if let Some(state) = self.correlation_states.get_mut(&canonical) {
            state.historical_mean = mean;
            state.historical_std = std.max(0.01); // Prevent division by zero
        }
    }
    
    /// Record return observation for an asset
    pub fn record_return(&mut self, asset: Asset, return_pct: f64, timestamp: Instant) {
        // Update all pairs containing this asset
        for pair in &self.monitored_pairs.clone() {
            if pair.base == asset || pair.quote == asset {
                // We need paired returns - in production, this would be synchronized
                // For now, we track individual asset returns and calculate correlation
                // when both sides have data
            }
        }
    }
    
    /// Record paired return observation
    pub fn record_paired_return(
        &mut self,
        pair: AssetPair,
        return_base: f64,
        return_quote: f64,
        timestamp: Instant,
    ) -> Option<CorrelationAlert> {
        let canonical = pair.canonical();
        
        if let Some(calculator) = self.calculators.get_mut(&canonical) {
            calculator.add(return_base, return_quote);
            
            // Update correlation state
            if let Some(state) = self.correlation_states.get_mut(&canonical) {
                state.current_correlation = calculator.correlation();
                state.sample_count = calculator.count;
                state.last_updated = timestamp;
                
                // Calculate z-score if we have baseline
                if let Some(&(mean, std)) = self.baselines.get(&canonical) {
                    state.z_score = (state.current_correlation - mean) / std;
                    
                    // Determine regime
                    state.regime = self.classify_regime(state.z_score);
                    
                    // Check for alerts
                    return self.check_alert_conditions(state);
                }
            }
        }
        
        None
    }
    
    /// Classify correlation regime based on z-score
    fn classify_regime(&self, z_score: f64) -> CorrelationRegime {
        let abs_z = z_score.abs();
        
        if abs_z > self.z_score_threshold * 2.0 {
            CorrelationRegime::Broken
        } else if abs_z > self.z_score_threshold {
            CorrelationRegime::Extreme
        } else if abs_z > self.z_score_threshold * 0.5 {
            CorrelationRegime::Elevated
        } else {
            CorrelationRegime::Normal
        }
    }
    
    /// Check conditions for generating alerts
    fn check_alert_conditions(&mut self, state: &CorrelationState) -> Option<CorrelationAlert> {
        // Only alert if we have enough samples
        if state.sample_count < self.min_samples {
            return None;
        }
        
        let alert = match state.regime {
            CorrelationRegime::Broken => {
                Some(self.create_alert(
                    state,
                    AlertType::CorrelationBreakdown,
                    Severity::Critical,
                    RecommendedAction::SuspendHedging,
                    format!(
                        "Correlation breakdown detected for {:?}: r={:.3}, z={:.2}",
                        state.pair, state.current_correlation, state.z_score
                    ),
                ))
            }
            CorrelationRegime::Extreme => {
                Some(self.create_alert(
                    state,
                    AlertType::RegimeChange,
                    Severity::High,
                    RecommendedAction::ReduceHedgeSize,
                    format!(
                        "Extreme correlation for {:?}: r={:.3}, z={:.2}",
                        state.pair, state.current_correlation, state.z_score
                    ),
                ))
            }
            CorrelationRegime::Elevated => {
                Some(self.create_alert(
                    state,
                    AlertType::CorrelationSpike,
                    Severity::Medium,
                    RecommendedAction::Monitor,
                    format!(
                        "Elevated correlation for {:?}: r={:.3}, z={:.2}",
                        state.pair, state.current_correlation, state.z_score
                    ),
                ))
            }
            CorrelationRegime::Normal => None,
        };
        
        // Auto-suspend hedging on critical alerts
        if let Some(ref a) = alert {
            if a.severity == Severity::Critical {
                self.suspend_pair(state.pair);
            }
        }
        
        alert
    }
    
    /// Create correlation alert
    fn create_alert(
        &self,
        state: &CorrelationState,
        alert_type: AlertType,
        severity: Severity,
        action: RecommendedAction,
        message: String,
    ) -> CorrelationAlert {
        CorrelationAlert {
            pair: state.pair,
            alert_type,
            severity,
            current_correlation: state.current_correlation,
            expected_correlation: state.historical_mean,
            z_score: state.z_score,
            timestamp: state.last_updated,
            message,
            recommended_action: action,
        }
    }
    
    /// Suspend hedging for a specific pair
    pub fn suspend_pair(&mut self, pair: AssetPair) {
        let canonical = pair.canonical();
        if !self.suspended_pairs.contains(&canonical) {
            self.suspended_pairs.push(canonical);
            
            self.alerts.push(CorrelationAlert {
                pair: canonical,
                alert_type: AlertType::HedgeFailure,
                severity: Severity::High,
                current_correlation: self.correlation_states
                    .get(&canonical)
                    .map(|s| s.current_correlation)
                    .unwrap_or(0.0),
                expected_correlation: self.baselines
                    .get(&canonical)
                    .map(|(m, _)| *m)
                    .unwrap_or(0.0),
                z_score: self.correlation_states
                    .get(&canonical)
                    .map(|s| s.z_score)
                    .unwrap_or(0.0),
                timestamp: Instant::now(),
                message: format!("Hedging suspended for {:?} due to correlation breakdown", canonical),
                recommended_action: RecommendedAction::SwitchHedgeInstrument,
            });
        }
    }
    
    /// Resume hedging for a pair
    pub fn resume_pair(&mut self, pair: AssetPair) {
        let canonical = pair.canonical();
        self.suspended_pairs.retain(|p| p != &canonical);
    }
    
    /// Check if hedging is safe for a pair
    pub fn is_hedge_safe(&self, pair: AssetPair) -> bool {
        let canonical = pair.canonical();
        
        // Check if suspended
        if self.suspended_pairs.contains(&canonical) {
            return false;
        }
        
        // Check regime
        if let Some(state) = self.correlation_states.get(&canonical) {
            return state.regime != CorrelationRegime::Broken;
        }
        
        true
    }
    
    /// Get all recent alerts
    pub fn get_alerts(&self, limit: usize) -> &[CorrelationAlert] {
        let start = self.alerts.len().saturating_sub(limit);
        &self.alerts[start..]
    }
    
    /// Get correlation state for a pair
    pub fn get_correlation_state(&self, pair: AssetPair) -> Option<&CorrelationState> {
        self.correlation_states.get(&pair.canonical())
    }
    
    /// Get current correlation value
    pub fn get_correlation(&self, pair: AssetPair) -> Option<f64> {
        self.correlation_states
            .get(&pair.canonical())
            .map(|s| s.current_correlation)
    }
    
    /// Clear old alerts to prevent memory buildup
    pub fn prune_alerts(&mut self, keep_last: usize) {
        if self.alerts.len() > keep_last {
            self.alerts.drain(..self.alerts.len() - keep_last);
        }
    }
}

impl Default for CorrelationBreaker {
    fn default() -> Self {
        Self::new(3.0, 30, 100) // Default: 3 std threshold, 30 min samples, 100 window
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn test_rolling_statistics() {
        let mut stats = RollingStatistics::new(5);
        
        for i in 1..=10 {
            stats.add(i as f64);
        }
        
        // After 10 additions with window 5, should have [6,7,8,9,10]
        assert_eq!(stats.count(), 5);
        assert!(stats.is_full());
        
        let mean = stats.mean();
        assert!((mean - 8.0).abs() < 0.01);
    }
    
    #[test]
    fn test_correlation_perfect_positive() {
        let mut calc = CorrelationCalculator::new(10);
        
        // Perfect positive correlation
        for i in 0..10 {
            let x = i as f64;
            let y = x * 2.0;
            calc.add(x, y);
        }
        
        let corr = calc.correlation();
        assert!((corr - 1.0).abs() < 0.01);
    }
    
    #[test]
    fn test_correlation_perfect_negative() {
        let mut calc = CorrelationCalculator::new(10);
        
        // Perfect negative correlation
        for i in 0..10 {
            let x = i as f64;
            let y = -x;
            calc.add(x, y);
        }
        
        let corr = calc.correlation();
        assert!((corr + 1.0).abs() < 0.01);
    }
    
    #[test]
    fn test_correlation_breaker_detection() {
        let mut breaker = CorrelationBreaker::new(2.0, 10, 50);
        
        let pair = AssetPair::new(Asset::BTC, Asset::ETH);
        breaker.add_pair(pair);
        
        // Set baseline: normally highly correlated
        breaker.set_baseline(pair, 0.8, 0.1);
        
        // Simulate normal correlation
        let now = Instant::now();
        for _ in 0..15 {
            let _ = breaker.record_paired_return(pair, 0.01, 0.008, now);
        }
        
        // Now simulate breakdown (correlation drops)
        for _ in 0..20 {
            let _ = breaker.record_paired_return(pair, 0.01, -0.01, now);
        }
        
        let state = breaker.get_correlation_state(pair).unwrap();
        assert!(state.z_score.abs() > 2.0, "Should detect correlation break");
    }
    
    #[test]
    fn test_hedge_suspension() {
        let mut breaker = CorrelationBreaker::new(2.0, 10, 50);
        
        let pair = AssetPair::new(Asset::BTC, Asset::ETH);
        breaker.add_pair(pair);
        breaker.set_baseline(pair, 0.8, 0.05); // Tight baseline
        
        let now = Instant::now();
        
        // Force extreme z-score
        for _ in 0..30 {
            let _ = breaker.record_paired_return(pair, 0.02, -0.02, now);
        }
        
        // Should have suspended hedging
        assert!(!breaker.is_hedge_safe(pair));
    }
}
